spring:
  application:
    name: consumer
  ## Import Aws Yml File
  config:
    import: aws-profile.yml, sqs-queue.yml, sns.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/default
    username: default
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
